# values.yaml for landing-frontend

replicaCount: 1
image:
  repository: ghcr.io/fitnest-code/landing-frontend
  tag: "production-e652ea8"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
networkPolicy:
  enabled: true
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: fitnest.az
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - fitnest.az
      secretName: fitnest-tls
  backend:
    service:
      name: "" # Empty means use the chart's fullname (landing-frontend)
      port: 80
resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 1000m
    memory: 384Mi
env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: "https://api.fitnest.az"
assetLinks:
  enabled: true
  secretName: assetlinks-secret
